[package]
name = "tls-from-scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
ser = { path = "ser" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
nom = "7.1"
enum-try-from = "0.0.1"
